# Generated by Django 3.0.5 on 2020-05-03 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200503_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 21, 51, 41, 608844, tzinfo=utc)),
        ),
    ]
