# Generated by Django 3.0.5 on 2020-05-04 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200505_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 19, 14, 46, 834484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
